version: '3.8'

services:
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=admin
      - ELASTIC_USERNAME=elastic
    ports:
      - "9200:9200"


