version: '3.8'

services:

  # Servicio Consul
  consul:
    image: hashicorp/consul:1.16.0
    container_name: consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:${CONSUL_PORT_WEB_UI}'     # Port For Consul Web UI
      - '8600:${CONSUL_PORT_SERVICE}'
      - '8600:8600/udp'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${CONSUL_PORT_WEB_UI}/" ]
      interval: 2s
      timeout: 2s
      retries: 10      
    env_file:
      - .env
    restart: always

  rabbitmq:
    image: rabbitmq:3-management   # Usa la versi贸n con interfaz de administraci贸n
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT_WEB_UI}:${RABBITMQ_PORT_WEB_UI}"
      - "${RABBITMQ_PORT_SERVICE}:${RABBITMQ_PORT_SERVICE}"

    volumes:
      - './keys:/etc/ssl/certs'   # Monta el directorio con los certificados
      - './rabbitmq:/etc/rabbitmq' # Configuraci贸n personalizada de RabbitMQ# Puerto para la interfaz de administraci贸n
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
    env_file:
      - .env
    restart: always
