version: '3.8'

services:

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "${HAPROXY_PORT}:${HAPROXY_PORT}"
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    environment:
      CONSUL_HOST: ${CONSUL_RABBITMQ_HOST_AWS}
      HAPROXY_PORT: ${HAPROXY_PORT}
      CONSUL_PORT_SERVICE: ${CONSUL_PORT_SERVICE}
      GRAFANA_PORT: ${GRAFANA_PORT}
      HAPROXY_STATS_PORT: ${HAPROXY_STATS_PORT}
    volumes:
      - './haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
      - ./haproxy.cfg/503_error.html:/usr/local/etc/haproxy/503_error.html
      - './keys:/keys'
    depends_on:
      - filebeat
    env_file:
      - .env

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://10.0.6.139:9200
    
    restart: always
