{
 "title": "Logs Dashboard",
 "description": "Logs Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Containers",
    "query": {}
   },
   { "name": "filter_msj", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Type Level Log",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"your-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"logs\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> group(columns: [\"log_level\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Errors over Time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"your-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"logs\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> filter(fn: (r) => r.log_level == \"ERROR\")\r\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Logs by exchange over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"your-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"logs\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> group(columns: [\"exchange\"])\r\n  |> aggregateWindow(every: 1h, fn: count, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}